# Generated by Django 3.1.6 on 2021-11-03 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='number_of_oages',
            new_name='number_of_pages',
        ),
    ]
